### ISSUE TITLE
Bug related to logging

### ISSUE THREAD

**Issue by nickmcdowall** [lsd-consulting/lsd-junit5#16]
Found this error in a Java 17 project that needs investigating.

It prevents the reports from being generated.

```-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@54e7df6a - Error during parser creation or parser configuration org.xml.sax.SAXNotRecognizedException: unrecognized feature http://xml.org/sax/features/external-general-entities
	at org.xml.sax.SAXNotRecognizedException: unrecognized feature http://xml.org/sax/features/external-general-entities
	at 	at org.gjt.xpp.sax2.Driver.setFeature(Driver.java:178)
	at 	at org.gjt.xpp.jaxp11.SAXParserImpl.setFeatures(SAXParserImpl.java:149)
	at 	at org.gjt.xpp.jaxp11.SAXParserImpl.<init>(SAXParserImpl.java:132)
	at 	at org.gjt.xpp.jaxp11.SAXParserFactoryImpl.newSAXParserImpl(SAXParserFactoryImpl.java:114)
	at 	at org.gjt.xpp.jaxp11.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:142)
	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:89)
	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:62)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.populateSaxEventRecorder(GenericXMLConfigurator.java:172)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:158)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:121)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:64)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:68)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:139)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:152)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at 	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
	at 	at com.lsd.properties.PropertiesLoader.<clinit>(PropertiesLoader.java:12)
	at 	at com.lsd.properties.LsdProperties.<clinit>(LsdProperties.java:19)
	at 	at com.lsd.LsdContext.<init>(LsdContext.java:33)
	at 	at com.lsd.LsdContext.<clinit>(LsdContext.java:27)
	at 	at io.lsdconsulting.junit5.LsdExtension.<init>(LsdExtension.java:32)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at 	at ...
```

**Comment by lukasz-gryzbon** [comment]
I'm not sure the problem is related to this project.

Found this: https://stackoverflow.com/questions/71910861/failed-to-auto-configure-default-logger-context-joranexception-parser-configu

This project doesn't seem to depend on `dom4j` or `pull-parser`.

I ran into the same issue in the `lsd-formatting-library` and [excluding the `pull-parser` lib](https://github.com/lsd-consulting/lsd-formatting-library/blob/9b84091c16abe7fa50b197fad2f2ba0806150d5d/build.gradle#L30) fixed the issue.
